% AvDiscrGF computes a free space Averaged Discrete Green's function 
% giving the electrostatic interaction between two rectangular cells of 
% identical dimensions a*b and located in the planes z=0 and z=zc, both  
% having sides parallel to the x and y axes. 
% The centers of the two cells are in (0,0,0) and (xc,yc,zc).  
 
% The computation is done by evaluating the normalized double surface (4D) 
% integral of the integrand 1/r, through the use of the primitive functions 
% prim1, prim2,prim3 and prim4 
 
% AvDiscrGF is to be used in Galerkin formulations. If the mean theorem is 
% used, AvDiscrGF can be approximated by the corresponding DiscrGF value 
 
% J. R. Mosig, EPFL Switzerland, 01/06/2023 
 
function [result] = AvDiscrGF(xc,yc,zc,a,b) 
 
zc=zc+eps; 
prim1 = @(u,v) u*asinh(v/sqrt(u^2+zc^2))+v*asinh(u/sqrt(v^2+zc^2))... 
      - zc*atan(u*v/(zc*sqrt(u^2+v^2+zc^2))); 
prim2 = @(u,v) (v*sqrt(u^2+v^2+zc^2)+(u^2+zc^2)*asinh(v/sqrt(u^2+zc^2)))/2; 
prim3 = @(u,v) (u*sqrt(u^2+v^2+zc^2)+(v^2+zc^2)*asinh(u/sqrt(v^2+zc^2)))/2; 
prim4 = @(u,v) (u^2+v^2+zc^2)^(3/2)/3; 
 
Yuu=(xc-a)*(yc-b)*definite(prim1,xc-a,xc,yc-b,yc)... 
    -(yc-b)*definite(prim2,xc-a,xc,yc-b,yc)... 
    -(xc-a)*definite(prim3,xc-a,xc,yc-b,yc)... 
    +definite(prim4,xc-a,xc,yc-b,yc); 
Yud=-(xc-a)*(yc+b)*definite(prim1,xc-a,xc,yc,yc+b)... 
    +(yc+b)*definite(prim2,xc-a,xc,yc,yc+b)... 
    +(xc-a)*definite(prim3,xc-a,xc,yc,yc+b)... 
    -definite(prim4,xc-a,xc,yc,yc+b); 
Ydu=-(xc+a)*(yc-b)*definite(prim1,xc,xc+a,yc-b,yc)... 
    +(yc-b)*definite(prim2,xc,xc+a,yc-b,yc)... 
    +(xc+a)*definite(prim3,xc,xc+a,yc-b,yc)... 
    -definite(prim4,xc,xc+a,yc-b,yc); 
Ydd=(xc+a)*(yc+b)*definite(prim1,xc,xc+a,yc,yc+b)... 
    -(yc+b)*definite(prim2,xc,xc+a,yc,yc+b)... 
    -(xc+a)*definite(prim3,xc,xc+a,yc,yc+b)... 
    +definite(prim4,xc,xc+a,yc,yc+b); 
result=(Yuu+Yud+Ydu+Ydd)/(a*b)^2; 
end